version: '3.1'
services:
  app:
    container_name: task
    image: task
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update